---
- hosts: All
  become: yes
  tasks:

  - name: copy timezone
    ansible.builtin.copy:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root

  - name: restart chronyd
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: yes

  - name: update the rpm
    ansible.builtin.dnf:
      name:
        - rpm
      state: latest
      update_only: yes

  - name: install packages
    ansible.builtin.yum: name={{ item }} state=latest
    with_items:
      - tcpdump
      - nano
      - mc

- hosts: Clients
  become: yes
  tasks:

  - name: correct file hosts
    ansible.builtin.shell:
      cmd: echo "192.168.56.10 ipa.otus.lan ipa" >> /etc/hosts

  - name: install packages
    ansible.builtin.yum: name={{ item }}
    with_items:
      - freeipa-client

  - name: add host to ipa
    ansible.builtin.shell:
      cmd: echo -e "yes\nyes" | ipa-client-install --mkhomedir --domain=OTUS.LAN --server=ipa.otus.lan --no-ntp -p admin -w 3edc4rfv


